### PR TITLE
AF-2132: Fixing offline build to use correct project

### PR DESCRIPTION
**Pull request by jesuino**
Suggested fix for RHPAM-2278.

### CODE REVIEW

**Comment by jesuino** [comment]
Jenkins execute full downstream build

**Comment by ederign** [comment]
@jesuino can you please add tests for this? Or the current coverage is enough?
@porcelli can you please review this?

**Comment by jesuino** [comment]
Hello @ederign @domhanak  I added an unit test for the change I made, please let me know if you have any question. 

Thanks for the feedback, @porcelli really appreciate

**Comment by jesuino** [comment]
Jenkins execute full downstream build

**Comment by domhanak** [comment]
@jesuino Fix works, I was able to complete steps without any issues. 

@porcelli Do you mind explaining `static MavenProject mavenProject;` field? I am having a hard time understanding it;s purpose.

**Comment by porcelli** [comment]
@domhanak I honestly don't know why this is designed as is. I'd design it totally different.

**Comment by domhanak** [comment]
@porcelli Nevermind, I wonder if the field still makes sense, but I would also like to understand how it works internally. 
The field is only used in `loadMavenProject` but that method is called in `org.appformer.maven.integration.Aether#getAether()` to create instance of Aether if it is null.
`Aether` also has public constructor in addition to `static instance` field, but loadMavenProject is not called there. This is really suspicious.
Is there any1 who could tell me how it works as whole?

**Comment by jesuino** [comment]
Hello @domhanak 

This specific method is called during a full build. To find the issue I made a lot of debug during project build. Today I made debug again to revisit the stack trace.

When the project is created (after creating or importing a project):
~~~
MavenProjectLoader.parseMavenPom(InputStream, boolean) line: 90	
MavenProjectLoader.parseMavenPom(InputStream) line: 84	
MavenPomModelGenerator.parse(String, InputStream) line: 34	
PomModel$Parser.parse(String, InputStream) line: 110	
KieBuilderImpl.buildPomModel() line: 568	
KieBuilderImpl.getPomModel() line: 545	
KieBuilderImpl.init() line: 153	
~~~

Or when resources are changed:
~~~
MavenProjectLoader.parseMavenPom(InputStream, boolean) line: 90	
MavenProjectLoader.parseMavenPom(InputStream) line: 84	
ModuleRepositoryResolverImpl.getRemoteRepositoriesMetaData(Module) line: 143	
ModuleRepositoryResolverImpl$Proxy$_$$_WeldClientProxy.getRemoteRepositoriesMetaData(Module) line: not available	
ModuleRepositoriesSynchronizer.syncModuleRepositories(Path) line: 109	
ModuleRepositoriesSynchronizer.onBatchResourceChanges(ResourceBatchChangesEvent) line: 87	
~~~
And when a full build is triggered 
~~~
MavenProjectLoader.parseMavenPom(InputStream, boolean) line: 90	
MavenProjectLoader.parseMavenPom(InputStream) line: 84	
ModuleRepositoryResolverImpl.getRemoteRepositoriesMetaData(Module) line: 143	
ModuleRepositoryResolverImpl$Proxy$_$$_WeldClientProxy.getRemoteRepositoriesMetaData(Module) line: not available	
ModuleRepositoriesSynchronizer.syncModuleRepositories(Path) line: 109	
ModuleRepositoriesSynchronizer.onResourceUpdated(ResourceUpdatedEvent) line: 80	
~~~

These methods from `ModuleRepositoriesSynchronizer` are called when events are fired.

If force offline is true then looks like we won't be going to internet at all, so the flag will trigger two process:

* First is make  all the WEB-INF/lib jars available into the internal maven repo;
* Second we need to add dependencies that we can resolve to the maven project. This part specifically I would have to analyze further, to see how artifacts are later used, but I know that what is in the artifacts field from maven project is what is used in the actual project classpath, hence making sure that the artifact is there will finally help to build the project. 

What I noticed during debug  with offline is that the list of artifacts was empty while it was correctly filled when offline was not true. My suspicious went to the maven repo, but then I noticed that the created maven project was not being used.

**Pull request merged**
