### PR TITLE
[DO NOT MERGE] Replace parent pom with kie-parent

### PR DESCRIPTION
**Pull request by baldimir**
Testing PR, how this will behave with downstream build. If I build this locally, all tests in kie-soup pass.

### CODE REVIEW

**Comment by baldimir** [comment]
jenkins execute full downstream build

**Comment by porcelli** [comment]
there were reasons in the past to not use kie-parent, but they're not valid anymore.

with that said, the order of this repo has to  be changed in the build

**Comment by baldimir** [comment]
jenkins execute full donwstream build

**Comment by baldimir** [comment]
jenkins execute full downstream build

**Comment by baldimir** [comment]
I will wait for fix from @porcelli that we discussed online and rerun this again after.

**Pull request closed without merging**
