### PR TITLE
AF-593+: Move dashbuilder to uberfire.

### PR DESCRIPTION
**Pull request by mbarkley**

### CODE REVIEW

**Comment by mbarkley** [comment]
Related:
https://github.com/kiegroup/kie-soup/pull/13
https://github.com/AppFormer/uberfire/pull/898
https://github.com/dashbuilder/dashbuilder/pull/396
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/599
https://github.com/kiegroup/jbpm/pull/1060
https://github.com/kiegroup/droolsjbpm-integration/pull/1260
https://github.com/kiegroup/kie-wb-common/pull/1279
https://github.com/kiegroup/drools-wb/pull/701
https://github.com/kiegroup/jbpm-wb/pull/938
https://github.com/kiegroup/optaplanner-wb/pull/237
https://github.com/kiegroup/kie-wb-distributions/pull/650

**Comment by mbarkley** [comment]
@ederign @dgutierr Not sure what to do about this failure. The issue is our elasticsearch and netty versions. Our version of elasticsearch (2.1.2) is not compatible with our version of netty (4.1.16.Final).

Do you have any advice on this? Can we safely upgrade elasticsearch?

//cc @psiroky

**Comment by dgutierr** [comment]
@romartin mind to look into this please?

**Comment by romartin** [comment]
@mbarkley Hey Max, well @adrielparedes just did the version upgrade for dashbuier's EL provider, so not sure if this is still necessary, we should be at same EL version as in the rest of the platform.

**Pull request closed without merging**
