### PR TITLE
AF-2276: Fixing is offline setting access (#116)

### PR DESCRIPTION
**Pull request by mareknovotny**
backport of #116

merge with https://github.com/kiegroup/kie-wb-common/pull/2997

### CODE REVIEW

**Comment by domhanak** [comment]
@mareknovotny I think you are missing kie-wb-common PR that was merged together with this one.
https://github.com/kiegroup/kie-wb-common/pull/2940

**Comment by mareknovotny** [comment]
here it is kiegroup/kie-wb-common/pull/2997 @domhanak

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by domhanak** [comment]
Jenkins execute full downstream build

**Comment by domhanak** [comment]
Jenkins execute full downstream build

**Comment by yurloc** [comment]
FDB completed, 1 unrelated test failed:

**org.kie.wb.selenium.ui.StandalonePerspectivesIntegrationTest.org.kie.wb.selenium.ui.StandalonePerspectivesIntegrationTest**
### Error Details

Could not create statement

### Stack Trace

java.lang.RuntimeException: Could not create statement
Caused by: org.jboss.arquillian.graphene.enricher.exception.PageObjectInitializationException: 
Can not instantiate Page Object 
class org.kie.wb.selenium.model.LoginPage
 declared in: 
org.kie.wb.selenium.ui.StandalonePerspectivesIntegrationTest

Caused by: java.lang.RuntimeException: 
Unable to instantiate Drone via org.openqa.selenium.firefox.FirefoxDriver(FirefoxOptions): org.openqa.selenium.WebDriverException: invalid argument: can't kill an exited process
Build info: version: '3.11.0', revision: 'e59cfb3', time: '2018-03-11T20:26:55.152Z'
System info: host: 'rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-1062.el7.x86_64', java.version: '1.8.0_202'
Driver info: driver.version: FirefoxDriver
remote stacktrace: 
Caused by: org.openqa.selenium.WebDriverException: 
invalid argument: can't kill an exited process
Build info: version: '3.11.0', revision: 'e59cfb3', time: '2018-03-11T20:26:55.152Z'
System info: host: 'rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-1062.el7.x86_64', java.version: '1.8.0_202'
Driver info: driver.version: FirefoxDriver
remote stacktrace:

**Pull request merged**
