### PR TITLE
AF-593+: Move uberfire-maven-utils to kie-soup

### PR DESCRIPTION
**Pull request by mbarkley**
Currently drools, droolsjbpm-knowledge, and others depend on the uberfire-maven-utils. This dependency prevents uberfire from being a consumer of the kie-api. By moving the maven-utils to kie-soup, uberfire can become a consumer of the kie-api which will be necessary for using the data-modeller as part of uberfire/appformer.

### CODE REVIEW

**Comment by manstis** [comment]
@mbarkley Was you planning on moving the ```XStreamUtils``` to ```KIE Soup``` too?

**Comment by mbarkley** [comment]
@manstis Yes. I will send that as it's own PR later today or tomorrow.

**Comment by mbarkley** [comment]
@manstis Maybe you were giving me a subtle hint, but these PRs can't possibly be merged before XStreamUtils is moved so I am working on that now :)

**Comment by mbarkley** [comment]
Related:
https://github.com/kiegroup/droolsjbpm-integration/pull/1247
https://github.com/kiegroup/kie-wb-distributions/pull/646
https://github.com/kiegroup/optaplanner-wb/pull/233
https://github.com/kiegroup/jbpm-wb/pull/934
https://github.com/kiegroup/drools-wb/pull/674
https://github.com/kiegroup/kie-wb-common/pull/1264
https://github.com/kiegroup/droolsjbpm-tools/pull/84
https://github.com/kiegroup/droolsjbpm-knowledge/pull/274
https://github.com/kiegroup/jbpm/pull/1045
https://github.com/kiegroup/drools/pull/1559
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/585
https://github.com/AppFormer/uberfire/pull/888
https://github.com/kiegroup/kie-soup/pull/8

**Comment by mbarkley** [comment]
@manstis @ederign I think these are good to merge now. All PRs are approved with green builds.

**Comment by manstis** [comment]
@mbarkley Did I miss any?

**Comment by mbarkley** [comment]
@manstis Nope, you got them all :)

**Pull request merged**
