### PR TITLE
AF-1967: Bringing SQL tests to kie-soup-dataset-sql-tests so individual tests will run

### PR DESCRIPTION
**Pull request by jesuino**
testAll does not show individual tests. With this PR we are bringing tests inside kie-soup-dataset-sql-tests, so each test will run individually.

To achieve this we used Java SPI

### CODE REVIEW

**Comment by domhanak** [comment]
Looks good. Thanks!

**Comment by paulovmr** [comment]
jenkins execute full downstream build

**Comment by jesuino** [comment]
Jenkins execute full downstream build

**Comment by paulovmr** [comment]
Jenkins execute full downstream build

**Comment by paulovmr** [comment]
jenkins retest this

**Comment by jesuino** [comment]
I think the test failure is unrelated to the clob tests - I see it time from time, it is intermittent:

https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/master/job/pullrequest/job/kie-soup-downstream-pullrequests/19/testReport/org.dashbuilder.dataset.service/DataSetExportServicesTest/exportToExcelWorksWhenDataSetHasNulls/

**Pull request merged**
