### PR TITLE
JBPM-8445: Stunner -  unable to set cycle timer with cron expression

### PR DESCRIPTION
**Pull request by wmedvede**
- Splits the CronExpression in drools into a GWT compatible part required by Stunner and the non GWT complatible methods remains in drools

### CODE REVIEW

**Comment by wmedvede** [comment]
To make the CronExpression available in Stunner (client side) it was necessary to do a small code split into one piece that is 100% GWT compatible/compilable and all the non GWT complatible methods in the other part of the split. But code is essentially the same as before, just some mehods placed in kie-soup and the rest of the methods remained in drools.

@mariofusco  @romartin  would you mind review this PR? 
Thanks!

**Comment by wmedvede** [comment]
jenkins execute full downstream build

**Comment by wmedvede** [comment]
Hi @mariofusco don't forget to take a look at this please.
Thanks.

**Comment by wmedvede** [comment]
Hi @baldimir would you mind prioritize this PR? We need to merge this into master and proceed with the cherry-pick into 7.4.1 asap.

Thanks!

**Comment by wmedvede** [comment]
Hi @baldimir sorry for chasing, but I'll will be asked for the status of this in today's scrum meeting. Any chance you can take a look at this?

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by wmedvede** [comment]
full-bld failed in non related stuff

Stacktrace
java.lang.NullPointerException
	at org.kie.server.integrationtests.drools.pmml.ApplyScorecardMultiModuleIntegrationTest.buildAndDeployArtifacts(ApplyScorecardMultiModuleIntegrationTest.java:44)
Standard Output
23:10:13.016 [main] INFO  org.codehaus.plexus.PlexusContainer - Installing /home/jenkins/workspace/KIE/master/pullrequest/kie-soup-downstream-pullrequests/downstream-repos/droolsjbpm-integration/kie-server-parent/kie-server-tests/kie-server-integ-tests-drools/target/test-classes/kjars-sources/common-parent/pom.xml to /home/jenkins/.m2/repository/org/kie/server/testing/common-parent/1.0.0.Final/common-parent-1.0.0.Final.pom
23:10:13.865 [main] INFO  o.k.a.i.utils.ServiceDiscoveryImpl - Loading kie.conf from  jar:file:/home/jenkins/.m2/repository/org/drools/drools-core/7.24.0-SNAPSHOT/drools-core-7.24.0-SNAPSHOT.jar!/META-INF/kie.conf in classloader ClassRealm[extension>org.kie:kie-maven-plugin:7.24.0-SNAPSHOT, parent: sun.misc.Launcher$AppClassLoader@3d4eac69]

**Comment by wmedvede** [comment]
jenkins execute full downstream build

**Comment by manstis** [comment]
Merging early (i.e. before FDB) as https://github.com/kiegroup/kie-wb-common/pull/2689 has been merged and we need all 3 in the ensemble merged....

**Pull request merged**
