### PR TITLE
[7.52.x] DROOLS-6268 : Guided Rule Editor: Add memberOf and not memberOf operators

### PR DESCRIPTION
**Pull request by Rikkola**
(cherry picked from commit 4fbacf9bfc58d03ea82ed0228a8acd55d44f0f8d)

**JIRA**: 

[DROOLS-6268](https://issues.redhat.com/browse/DROOLS-6268)

**referenced Pull Requests**:

* https://github.com/kiegroup/kie-soup/pull/194
* https://github.com/kiegroup/drools/pull/3689
* https://github.com/kiegroup/kie-wb-common/pull/3620
* https://github.com/kiegroup/drools-wb/pull/1483

### CODE REVIEW

**Review by jomarko — APPROVED** [review]

**Review by karreiro — APPROVED** [review]

**Comment by mareknovotny** [comment]
jenkins do fdb

**Comment by mareknovotny** [comment]
jenkins do fdb

**Comment by mareknovotny** [comment]
closing as the jira was retargeted only to master branch

**Comment by mareknovotny** [comment]
jenkins do fdb

**Comment by Rikkola** [comment]
@mareknovotny Hey I was going to say that! ;)

**Comment by mareknovotny** [comment]
jenkins do fdb

**Comment by mareknovotny** [comment]
FDB was timed out just before finishing, There is no failure, only **org.kie.wb.selenium.ui.ProjectLibraryIntegrationTest** in error.

```
[2021-06-29T01:22:59.036Z] [ERROR] Tests run: 3, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 273.308 s <<< FAILURE! - in org.kie.wb.selenium.ui.ProjectLibraryIntegrationTest
[2021-06-29T01:22:59.036Z] [ERROR] importAndBuildProjectFromStockRepository(org.kie.wb.selenium.ui.ProjectLibraryIntegrationTest)  Time elapsed: 76.196 s  <<< ERROR!
[2021-06-29T01:22:59.036Z] org.openqa.selenium.TimeoutException: Expected condition failed: waiting for presence of element located by: By.id: add-project-dropdown (tried for 15 second(s) with 500 milliseconds interval)
[2021-06-29T01:22:59.036Z] 	at org.kie.wb.selenium.ui.ProjectLibraryIntegrationTest.lambda$importAndBuildProjectFromStockRepository$0(ProjectLibraryIntegrationTest.java:51)
[2021-06-29T01:22:59.037Z] 	at org.kie.wb.selenium.ui.ProjectLibraryIntegrationTest.importBuildDeployAndCheckArtifact(ProjectLibraryIntegrationTest.java:68)
[2021-06-29T01:22:59.037Z] 	at org.kie.wb.selenium.ui.ProjectLibraryIntegrationTest.importAndBuildProjectFromStockRepository(ProjectLibraryIntegrationTest.java:49)
[2021-06-29T01:22:59.037Z] Caused by: org.openqa.selenium.NoSuchElementException: 
[2021-06-29T01:22:59.037Z] Cannot locate an element using By.id: add-project-dropdown
[2021-06-29T01:22:59.037Z] For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
[2021-06-29T01:22:59.037Z] Build info: version: '3.11.0', revision: 'e59cfb3', time: '2018-03-11T20:26:55.152Z'
[2021-06-29T01:22:59.037Z] System info: host: 'eng-jenkins-csb-business-automation.apps.ocp4.prod.psi.redhat.com', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-1160.25.1.el7.x86_64', java.version: '1.8.0_292'
[2021-06-29T01:22:59.037Z] Driver info: driver.version: unknown
[2021-06-29T01:22:59.037Z] 	at org.kie.wb.selenium.ui.ProjectLibraryIntegrationTest.lambda$importAndBuildProjectFromStockRepository$0(ProjectLibraryIntegrationTest.java:51)
[2021-06-29T01:22:59.037Z] 	at org.kie.wb.selenium.ui.ProjectLibraryIntegrationTest.importBuildDeployAndCheckArtifact(ProjectLibraryIntegrationTest.java:68)
[2021-06-29T01:22:59.037Z] 	at org.kie.wb.selenium.ui.ProjectLibraryIntegrationTest.importAndBuildProjectFromStockRepository(ProjectLibraryIntegrationTest.java:49)
```

**Pull request merged**
