### PR TITLE
AF-1528 revert

### PR DESCRIPTION
**Pull request by porcelli**
These PRs should be merged all together:

https://github.com/kiegroup/kie-soup/pull/65
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/839
https://github.com/kiegroup/appformer/pull/470
https://github.com/kiegroup/kie-wb-common/pull/2135
https://github.com/kiegroup/kie-wb-distributions/pull/818
https://github.com/kiegroup/kie-docs/pull/1094

### CODE REVIEW

**Comment by porcelli** [comment]
jenkins execute full downstream build

**Comment by jhrcek** [comment]
Most of the failures are kie-server integration tests that I just sent email about to bsig-all. One of them is "port already used" Maven integraion test. Not sure if we need another full downstream build but I'll start it anyway to save time :) 
Jenkins execute full downstream build

**Comment by porcelli** [comment]
I'm good to merge as is. wait for gree these days is getting hard... easy to win lottery :)

**Comment by jhrcek** [comment]
Let's just do sanity check with @sutaakar that it's Ok to merge this even with these 44 kie server test failures..

**Comment by mbiarnes** [comment]
@jhrcek @sutaakar please let me know what is your conclusion with sanity checks
All these PRs have to be merged for CR2

**Pull request merged**
