### PR TITLE
Remove log4j-api and log4j-core references

### PR DESCRIPTION
**Pull request by jomarko**

### CODE REVIEW

**Comment by jomarko** [comment]
Jenkins do fdb

**Review by manstis — APPROVED** [review]

**Comment by jomarko** [comment]
Jenkins do fdb

**Review by mareknovotny — APPROVED** [review]

**Comment by mareknovotny** [comment]
some glitch in CI, needed to cancel all 17 days running jobs

jenkins retest this please

**Comment by mareknovotny** [comment]
jenkins do fdb

**Comment by mareknovotny** [comment]
time out reached in kie-wb-distribution repo build

jenkins do fdb

**Comment by jomarko** [comment]
```
00:39:25  Cannot contact rhos-d-kie-rhel7-xlarge-xmem-96: java.lang.InterruptedException
03:29:37  Cancelling nested steps due to timeout
03:29:37  Could not connect to rhos-d-kie-rhel7-xlarge-xmem-96 to send interrupt signal to process
[Pipeline] }
03:29:37  rhos-d-kie-rhel7-xlarge-xmem-96 was marked offline: Connection was broken: java.io.EOFException
03:29:37  	at java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2798)
03:29:37  	at java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:3273)
03:29:37  	at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:933)
03:29:37  	at java.io.ObjectInputStream.<init>(ObjectInputStream.java:395)
03:29:37  	at hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:49)
03:29:37  	at hudson.remoting.Command.readFrom(Command.java:142)
03:29:37  	at hudson.remoting.Command.readFrom(Command.java:128)
03:29:37  	at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:35)
03:29:37  	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:61)
03:29:37  Caused: java.io.IOException: Unexpected termination of the channel
03:29:37  	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:75)
03:29:37  
[Pipeline] // withCredentials
[Pipeline] }
03:29:37  rhos-d-kie-rhel7-xlarge-xmem-96 was marked offline: Connection was broken: java.io.EOFException
03:29:37  	at java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2798)
03:29:37  	at java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:3273)
03:29:37  	at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:933)
03:29:37  	at java.io.ObjectInputStream.<init>(ObjectInputStream.java:395)
03:29:37  	at hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:49)
03:29:37  	at hudson.remoting.Command.readFrom(Command.java:142)
03:29:37  	at hudson.remoting.Command.readFrom(Command.java:128)
03:29:37  	at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:35)
03:29:37  	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:61)
03:29:37  Caused: java.io.IOException: Unexpected termination of the channel
03:29:37  	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:75)
```

**Comment by jomarko** [comment]
Jenkins do fdb

**Comment by jomarko** [comment]
Jenkins do fdb

**Comment by jomarko** [comment]
Jenkins do fdb

**Comment by jomarko** [comment]
Jenkins do fdb

**Comment by jomarko** [comment]
@mareknovotny please merge

**Pull request merged**
