### PR TITLE
[AF-1145]: Container removed if exist before test

### PR DESCRIPTION
**Pull request by adrielparedes**
@mbiarnes @mareknovotny Would you mind to review?

### CODE REVIEW

**Comment by mareknovotny** [comment]
first thing is why we have duplicate ElasticSearchTestSuite here and in https://github.com/kiegroup/appformer/pull/286 
Second, the issue https://issues.jboss.org/browse/AF-962 is still there so not locally possible for me to check the whole test suite.

**Comment by adrielparedes** [comment]
@mareknovotny as far as I knew when I did those tests was that they cannot depend on each other (apformer <-> kie-soup). And with second let me see if I can find something, but you can try it in fedora doing a "sudo setenforce 0" to put SELinux into Permissive.

**Comment by adrielparedes** [comment]
@mareknovotny it looks that I could remove elasticsearch.yml from here too, so try it again to see if we still have SELinux problem please.

**Comment by mareknovotny** [comment]
@adrielparedes thanks, it passes for me locally now

**Pull request merged**
