### PR TITLE
Adds missing kie-soup-project-datamodel-commons/src/main/resources/META-INF/beans.xml

### PR DESCRIPTION
**Pull request by wmedvede**
- This beans.xml is required since the MVELEvaluator is being Injected in some kie-wb-commons components

### CODE REVIEW

**Comment by wmedvede** [comment]
Hello @manstis would you mind review/merge. 
We have components in kie-wb-commons like EnumDropdownServiceImpl that are injecting the MVELEvaluator and for make this work the beans.xml is necessary.
Thanks.

**Comment by manstis** [comment]
@wmedvede The fix is to include ```drools-cdi``` dependency in your webapp.

This contains a CDI producer for the correct implementation of ```MVELEvaluator```

See https://github.com/kiegroup/drools-wb/pull/659

**Comment by manstis** [comment]
@wmedvede This was completed for ```drools-wb-webapp``` yesterday (as I had the same problem.. and I too started with considering changes in ```kie-soup```....). I believe @tiagodolphine is making similar changes to Stunner's webapps.

**Comment by wmedvede** [comment]
oh, good info.
Thanks

**Comment by tiagodolphine** [comment]
@wmedvede @manstis yeah, I just needed to add the `drools-cli`, but I need to exclude the `drools-compiler` from it, probably it was causing a conflict then  gwt was not compiling.
I will open a PR to fix this on Stunner webapps.

```
<dependency>
      <groupId>org.drools</groupId>
      <artifactId>drools-cdi</artifactId>
      <exclusions>
        <exclusion>
          <groupId>org.drools</groupId>
          <artifactId>drools-compiler</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
```
c/c @romartin

**Pull request closed without merging**
