### PR TITLE
DROOLS-6268 : Fix for GRE in

### PR DESCRIPTION
**Pull request by Rikkola**
**JIRA**:  

[DROOLS-6268](https://issues.redhat.com/browse/DROOLS-6268)

**referenced Pull Requests**: 

* https://github.com/kiegroup/kie-soup/pull/193
* https://github.com/kiegroup/drools/pull/3524
* https://github.com/kiegroup/kie-wb-common/pull/3619
* https://github.com/kiegroup/drools-wb/pull/1481

### CODE REVIEW

**Review by jomarko — APPROVED** [review]

**Review by karreiro — APPROVED** [review]
Thank you for the updates, @Rikkola!

**Comment by Rikkola** [comment]
Jenkins run fdb

**Comment by mareknovotny** [comment]
jenkins do fdb

**Comment by mareknovotny** [comment]
jenkins do fdb

**Comment by mareknovotny** [comment]
jenkins do fdb

**Comment by mareknovotny** [comment]
failures are not related to the changes (karaf test cannot find a dependency, jbpm human task test assertion)

**Pull request merged**
