### PR TITLE
Update the extra-enforcer-rules version to 1.0

### PR DESCRIPTION
**Pull request by tmckayus**

### CODE REVIEW

**Comment by tmckayus** [comment]
Diffing the source jars between extra-enforcer-rules-1.0-beta-4 and extra-enforcer-rules-1.0-beta-4-jbossorg-1 shows that the difference between the two was included in the 1.0-beta-5.

Therefore, the specific jbossorg-1 version is not necessary and the version should be updated so that this dependency can be found in maven central.

Since version 1.0 was recently released after 12 betas, that's  probably a good choice. At the very least, the version should be updated to 1.0-beta-5.

For reference
https://repository.jboss.org/nexus/index.html#nexus-search;quick~extra-enforcer-rules
https://github.com/mojohaus/extra-enforcer-rules/commit/ba4c4156372795bf7506b336e134fe71f90d5bf8

**Comment by tmckayus** [comment]
Note, the beta-4-jbossorg-1 version is also referenced in appformer, so a corresponding change should be made there as well assuming this is approved.

**Comment by kiereleaseuser2** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by kiereleaseuser2** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by kiereleaseuser2** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by kiereleaseuser2** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by mareknovotny** [comment]
ok to test

**Pull request merged**
