### PR TITLE
AF-2145: Fix kie-soup issues from sonar analysis

### PR DESCRIPTION
**Pull request by domhanak**
@jesuino @ederign Please take a look :) 

It should get rid of 3 out of 5 blockers from  - https://sonarcloud.io/project/issues?id=kiegroup_kie-soup&resolved=false&types=BUG  and some major issues.
2 remaining blockers are marked as won't fix.

### CODE REVIEW

**Comment by domhanak** [comment]
Roses are red,
violets are blue,
Jenkins execute full downstream build!

**Comment by domhanak** [comment]
Roses are red,
violets are blue,
Jenkins execute full downstream build!

**Comment by domhanak** [comment]
Jenkins execute full downstream build!

**Comment by jesuino** [comment]
The changes looks great to me @domhanak ! thanks for the improvements

**Comment by domhanak** [comment]
Jenkins execute full downstream build!

**Comment by domhanak** [comment]
Jenkins execute full downstream build!

**Comment by domhanak** [comment]
@paulovmr feel free to merge this when green

**Comment by paulovmr** [comment]
Unrelated test failures.

**Pull request merged**
