### PR TITLE
[BXMSPROD-1845] kie-soup-dataset-elasticsearch removed kie-soup

### PR DESCRIPTION
**Pull request by mareknovotny**
This is a follow up on PR #263 where @tomasdavidorg suggested to clean up also other remaining classes and commented code.

https://issues.redhat.com/browse/AF-2944

**referenced Pull Requests**: 
* merge together with https://github.com/kiegroup/appformer/pull/1375

* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2177
* https://github.com/kiegroup/kie-soup/pull/259

<details>
<summary>
How to backport a pull request to a different branch?
</summary>

In order to automatically create a **backporting pull request** please add one or more labels having the following format `backport-<branch-name>`, where `<branch-name>` is the name of the branch where the pull request must be backported to (e.g., `backport-7.67.x` to backport the original PR to the `7.67.x` branch).

> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release branch. Keeping it simple: it is about to move a specific change or a set of them from one branch to another.

Once the original pull request is successfully merged, the automated action will create one backporting pull request per each label (with the previous format) that has been added.

If something goes wrong, the author will be notified and at this point a manual backporting is needed.

> **NOTE**: this automated backporting is triggered whenever a pull request on `main` branch is labeled or closed, but both conditions must be satisfied to get the new PR created.
</details>

### CODE REVIEW

**Comment by mareknovotny** [comment]
jenkins do cdb

**Comment by mareknovotny** [comment]
jenkins retest this please

**Comment by mareknovotny** [comment]
jenkins do cdb

**Review by tomasdavidorg — CHANGES_REQUESTED** [review]
Hi @mareknovotny thanks for the PR. I think we should also remove:

- ElasticSearchDataSetDefBuilder class: https://github.com/mareknovotny/kie-soup/blob/pr-263/kie-soup-dataset/kie-soup-dataset-api/src/main/java/org/dashbuilder/dataset/def/ElasticSearchDataSetDefBuilder.java
- commented ElasticSearch version: https://github.com/mareknovotny/kie-soup/blob/pr-263/pom.xml#L54
- Some mentions in kie-soup-dataset/kie-soup-dataset-core/README.md: https://github.com/mareknovotny/kie-soup/blob/pr-263/kie-soup-dataset/kie-soup-dataset-core/README.md
- https://github.com/mareknovotny/kie-soup/blob/pr-263/kie-soup-dataset/kie-soup-dataset-api/src/main/resources/META-INF/ErraiApp.properties#L43
- Maybe the dependency is also not needed: https://github.com/mareknovotny/kie-soup/blob/pr-263/pom.xml#L474

**Comment by mareknovotny** [comment]
jenkins do fdb

**Review by tomasdavidorg — APPROVED** [review]
Thanks @mareknovotny. Looks good to me when the build is green.

**Comment by mareknovotny** [comment]
2 failures in tests related to this change:
```
Exception List with 1 exceptions:
Exception 0 :
java.lang.RuntimeException: failed to instantiate new type: org.jboss.errai.config.rebind.EnvUtil$EnvironmentConfigCache
 at org.jboss.errai.common.rebind.CacheUtil.getCache(CacheUtil.java:46)
 at org.jboss.errai.config.rebind.EnvUtil.getEnvironmentConfig(EnvUtil.java:375)
 at org.jboss.errai.config.rebind.EnvUtil.isUserPortableType(EnvUtil.java:388)
 at org.jboss.errai.config.rebind.EnvUtil.isPortableType(EnvUtil.java:380)
 at org.jboss.errai.cdi.server.CDIExtensionPoints.processObserverMethod(CDIExtensionPoints.java:259)
 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.base/java.lang.reflect.Method.invoke(Method.java:566)
 at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:95)
 at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:85)
 at org.jboss.weld.injection.MethodInvocationStrategy$SimpleMethodInvocationStrategy.invoke(MethodInvocationStrategy.java:168)
 at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:330)
 at org.jboss.weld.event.ExtensionObserverMethodImpl.sendEvent(ExtensionObserverMethodImpl.java:123)
 at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:308)
 at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:286)
 at javax.enterprise.inject.spi.ObserverMethod.notify(ObserverMethod.java:124)
 at org.jboss.weld.util.Observers.notify(Observers.java:166)
 at org.jboss.weld.event.ObserverNotifier.notifySyncObservers(ObserverNotifier.java:285)
 at org.jboss.weld.event.ObserverNotifier.notify(ObserverNotifier.java:273)
 at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:177)
 at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:171)
 at org.jboss.weld.bootstrap.events.AbstractContainerEvent.fire(AbstractContainerEvent.java:53)
 at org.jboss.weld.bootstrap.events.AbstractDefinitionContainerEvent.fire(AbstractDefinitionContainerEvent.java:44)
 at org.jboss.weld.bootstrap.events.ProcessObserverMethodImpl.fire(ProcessObserverMethodImpl.java:49)
 at org.jboss.weld.bootstrap.events.ProcessObserverMethodImpl.fire(ProcessObserverMethodImpl.java:45)
 at org.jboss.weld.bootstrap.events.ContainerLifecycleEvents.fireProcessObserverMethod(ContainerLifecycleEvents.java:315)
 at org.jboss.weld.bootstrap.events.ContainerLifecycleEvents.fireProcessObserverMethod(ContainerLifecycleEvents.java:302)
 at org.jboss.weld.bootstrap.AbstractBeanDeployer.deployObserverMethods(AbstractBeanDeployer.java:174)
 at org.jboss.weld.bootstrap.BeanDeployer.deploy(BeanDeployer.java:334)
 at org.jboss.weld.bootstrap.BeanDeployment.deployBeans(BeanDeployment.java:264)
 at org.jboss.weld.bootstrap.WeldStartup.deployBeans(WeldStartup.java:453)
 at org.jboss.weld.bootstrap.WeldBootstrap.deployBeans(WeldBootstrap.java:86)
 at org.jboss.weld.environment.se.Weld.initialize(Weld.java:814)
 at org.kie.workbench.common.forms.integration.tests.modelslookup.AbstractGetModelsTest.containerSetup(AbstractGetModelsTest.java:74)
 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.base/java.lang.reflect.Method.invoke(Method.java:566)
 at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
 at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
 at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
 at org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33)
 at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
 at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
 at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
 at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
 at org.mockito.internal.runners.DefaultInternalRunner$1.run(DefaultInternalRunner.java:99)
 at org.mockito.internal.runners.DefaultInternalRunner.run(DefaultInternalRunner.java:105)
 at org.mockito.internal.runners.StrictRunner.run(StrictRunner.java:40)
 at org.mockito.junit.MockitoJUnitRunner.run(MockitoJUnitRunner.java:163)
 at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
 at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
 at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
 at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
 at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
 at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
 at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
 at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
Caused by: java.lang.RuntimeException: could not find class defined in ErraiApp.properties for serialization: org.dashbuilder.dataprovider.ELSProviderType
 at org.jboss.errai.config.rebind.EnvUtil.addSerializableTypes(EnvUtil.java:289)
 at org.jboss.errai.config.rebind.EnvUtil.processErraiAppPropertiesBundle(EnvUtil.java:211)
 at org.jboss.errai.config.rebind.EnvUtil.processErraiAppPropertiesFiles(EnvUtil.java:184)
 at org.jboss.errai.config.rebind.EnvUtil.newEnvironmentConfig(EnvUtil.java:142)
 at org.jboss.errai.config.rebind.EnvUtil.access$000(EnvUtil.java:52)
 at org.jboss.errai.config.rebind.EnvUtil$EnvironmentConfigCache.clear(EnvUtil.java:63)
 at org.jboss.errai.config.rebind.EnvUtil$EnvironmentConfigCache.<init>(EnvUtil.java:58)
 at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
 at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
 at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
 at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
 at java.base/java.lang.Class.newInstance(Class.java:584)
 at org.jboss.errai.common.rebind.CacheUtil.getCache(CacheUtil.java:42)
 ... 58 more
Caused by: java.lang.RuntimeException: Could not load class: org.dashbuilder.dataprovider.ELSProviderType
 at org.jboss.errai.codegen.meta.MetaClassFactory.loadClass(MetaClassFactory.java:553)
 at org.jboss.errai.codegen.meta.MetaClassFactory.createOrGet(MetaClassFactory.java:228)
 at org.jboss.errai.codegen.meta.MetaClassFactory.createOrGet(MetaClassFactory.java:194)
 at org.jboss.errai.codegen.meta.MetaClassFactory.get(MetaClassFactory.java:129)
 at org.jboss.errai.config.rebind.EnvUtil.addSerializableTypes(EnvUtil.java:285)
 ... 70 more
```

**Comment by mareknovotny** [comment]
jenkins do fdb

**Comment by mareknovotny** [comment]
jenkins do fdb

**Comment by mareknovotny** [comment]
2 runs of FDB:

1. 4 failures in Kie server and jbpm tests
2. 5 failures, the same test failures as in 1. + LoadBalancer known as flaky

jenkins do fdb

**Comment by mareknovotny** [comment]
jenkins do fdb

previous run crashed due no space left on Jenkins

**Comment by jesuino** [comment]
Just a note: I am not able to see the failed tests in our CI server. It is failing with 504

**Comment by mareknovotny** [comment]
> Just a note: I am not able to see the failed tests in our CI server. It is failing with 504

yeah, there is this annoying error for builds big enough to render the summary job run page, but you can go directly to test report or to plain build log.
@winklerm  @mbiarnes did we have any idea how to fix this problem on Jenkins?

**Comment by mareknovotny** [comment]
so the both `org.jbpm.test.functional.CorrelationKeyTest` failures are on main too and there is already a PR to fix them https://github.com/kiegroup/jbpm/pull/2264

jenkins do fdb

**Comment by mareknovotny** [comment]
jenkins do fdb

**Comment by mareknovotny** [comment]
jenkins do fdb

**Pull request merged**
