### PR TITLE
Fix some deprecation warnings

### PR DESCRIPTION
**Pull request by jhrcek**
@dgutierr  please check. My console is all yellow, when compiling this project. Fix some compiler / deprecation warnings.

### CODE REVIEW

**Comment by jhrcek** [comment]
Real changes (ignoring formatting and imports):

```
IOUtils.toString(fileURL);  -> IOUtils.toString(fileURL, StandardCharsets.UTF_8);

Character.isSpace -> Character.isWhitespace

DataSetFactory.newDataSetLookupBuilder() -> DataSetLookupFactory.newDataSetLookupBuilder()
```

**Comment by mareknovotny** [comment]
Why Are we waiting with merging this as I see it good to have it in any case to reduce warnings from build?

**Comment by manstis** [comment]
@mareknovotny Quite simply I guess that nobody has actually asked anybody to merge it.

@dgutierr @jhrcek I assume this can be merged, but please confirm.

**Comment by jhrcek** [comment]
@manstis I completely forgot about this. You can merge it. Thank you

**Pull request merged**
