### PR TITLE
[7.26.x] AF-2245: Dashbuilder not closing ResultSets and Statements (#113)

### PR DESCRIPTION
**Pull request by jesuino**
* AF-2245: Dashbuilder not closing ResultSets and Statements

* AF-2245: Making ResultSetHandler AutoCloseable

### CODE REVIEW

**Comment by jesuino** [comment]
Jenkins execute full downstream build

**Comment by paulovmr** [comment]
Jenkins execute full downstream build

**Comment by jesuino** [comment]
Jenkins execute full downstream build

**Comment by jesuino** [comment]
Jenkins execute full downstream build

**Pull request merged**
