### PR TITLE
DROOLS-5883: Allow contains operator for string fields

### PR DESCRIPTION
**Pull request by jomarko**
Guided decision table and guided rule editor will ofer 'contains' operator also for string fields

For more details see https://issues.redhat.com/browse/DROOLS-5883

Ensemble together with:
- https://github.com/kiegroup/drools/pull/3281
- https://github.com/kiegroup/drools-wb/pull/1448

### CODE REVIEW

**Review by Rikkola — CHANGES_REQUESTED** [review]
Based on the doc ( I had to check ) we also have "not contains" and it should probably be added.

**Comment by jomarko** [comment]
@Rikkola thank you, good point, added

**Review by Rikkola — APPROVED** [review]

**Comment by jomarko** [comment]
@jstastny-cz just a friendly reminder if you could have a look on this. However understand this is targeted for 7.11.0 GA and has lower priority.

**Review by jstastny-cz — APPROVED** [review]

**Comment by jomarko** [comment]
@kiegroup/gatekeepers please merge

**Pull request merged**
