### PR TITLE
[7.23.x] JBPM-8445: Stunner -  unable to set cycle timer with cron expression

### PR DESCRIPTION
**Pull request by wmedvede**
- Splits the CronExpression in drools into a GWT compatible part required by Stunner and the non GWT complatible methods remains in drools

(cherry picked from commit 9e6d8a6f41e29ce28da10a81b1643486b9bead37)

### CODE REVIEW

**Comment by wmedvede** [comment]
jenkins execute full downstream build

**Comment by wmedvede** [comment]
full-build failed in non related tests
java.awt.AWTError: Can't connect to X11 window server using ':56' as the value of the DISPLAY variable.
	at sun.awt.X11GraphicsEnvironment.initDisplay(Native Method)
	at sun.awt.X11GraphicsEnvironment.access$200(X11GraphicsEnvironment.java:65)
	at sun.awt.X11GraphicsEnvironment$1.run(X11GraphicsEnvironment.java:115)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.awt.X11GraphicsEnvironment.<clinit>(X11GraphicsEnvironment.java:74)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at java.awt.GraphicsEnvironment.createGE(GraphicsEnvironment.java:103)
	at java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:82)
	at sun.awt.X11FontManager.isHeadless(X11FontManager.java:509)
	at sun.awt.X11FontManager.getFontPath(X11FontManager.java:786)
	at sun.font.SunFontManager.getPlatformFontPath(SunFontManager.java:3282)
	at sun.font.SunFontManager$10.run(SunFontManager.java:3308)

**Comment by wmedvede** [comment]
jenkins execute full downstream build

**Comment by wmedvede** [comment]
full-build failed in non related tests

org.jbpm.executor.impl.wih.AsyncContinuationSupportTest.testAsyncModeWithParallelGateway
org.kie.wb.selenium.ui.LoginIntegrationTest.loginAndLogout
org.kie.wb.selenium.ui.StandalonePerspectivesIntegrationTest.testStandaloneEditorPerspective
org.kie.wb.selenium.ui.StandalonePerspectivesIntegrationTest.testLibraryPerspectiveWithHeader
org.dashbuilder.dataset.service.DataSetExportServicesTest.exportToExcelWorksWhenDataSetHasNulls
org.kie.wb.selenium.ui.LoadAllPerspectivesIntegrationTest.allPerspectivesCanBeLoaded
org.kie.wb.selenium.ui.ProjectLibraryIntegrationTest.importAndBuildProjectFromCustomRepository

**Comment by wmedvede** [comment]
jenkins execute full downstream build

**Comment by wmedvede** [comment]
@romartin @tsurdilo 

I believe this PR can probably benefited form the changes proposed here https://github.com/kiegroup/jbpm/pull/1514 since I could see org.jbpm.executor.impl.wih.AsyncContinuationSupportTest.testAsyncModeWithParallelGateway is one of the failing tests.

WDYT @tsurdilo @mswiderski ?

**Comment by wmedvede** [comment]
now it failed because of this:

11:06:03 Unexpected error while executing the Downstream repositories builder for PR builds! Error while executing Maven process!
11:06:03 java.lang.RuntimeException: Error while executing Maven process!
11:06:03 	at org.kie.jenkinsci.plugins.kieprbuildshelper.MavenProject.build(MavenProject.java:65)
11:06:03 	at org.kie.jenkinsci.plugins.kieprbuildshelper.AbstractPRBuilder.perform(AbstractPRBuilder.java:130)
11:06:03 	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
11:06:03 	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
11:06:03 	at hudson.model.Build$BuildExecution.build(Build.java:206)
11:06:03 	at hudson.model.Build$BuildExecution.doRun(Build.java:163)
11:06:03 	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504)
11:06:03 	at hudson.model.Run.execute(Run.java:1724)
11:06:03 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
11:06:03 	at hudson.model.ResourceController.execute(ResourceController.java:97)
11:06:03 	at hudson.model.Executor.run(Executor.java:429)
11:06:03 Caused by: java.io.IOException: Backing channel 'kie-psi-rhel7-xlarge-xmem-112648' is disconnected.
11:06:03 	at hudson.remoting.RemoteInvocationHandler.channelOrFail(RemoteInvocationHandler.java:212)
11:06:03 	at hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:281)
11:06:03 	at com.sun.proxy.$Proxy97.isAlive(Unknown Source)
11:06:03 	at hudson.Launcher$RemoteLauncher$ProcImpl.isAlive(Launcher.java:1138)
11:06:03 	at hudson.Launcher$RemoteLauncher$ProcImpl.join(Launcher.java:1130)
11:06:03 	at org.kie.jenkinsci.plugins.kieprbuildshelper.MavenProject.build(MavenProject.java:63)
11:06:03 	... 10 more
11:06:03 Caused by: java.io.IOException: Unexpected termination of the channel
11:06:03 	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:77)
11:06:03 Caused by: java.io.EOFException
11:06:03 	at java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2680)
11:06:03 	at java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:3155)
11:06:03 	at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:861)
11:06:03 	at java.io.ObjectInputStream.<init>(ObjectInputStream.java:357)
11:06:03 	at hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:48)
11:06:03 	at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:35)
11:06:03 	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:63)

**Comment by wmedvede** [comment]
jenkins execute full downstream build

**Comment by wmedvede** [comment]
unexpected broken channel error again

11:44:07 	... 10 more
11:44:07 Caused by: java.io.IOException: Unexpected termination of the channel
11:44:07 	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:77)
11:44:07 Caused by: java.io.EOFException
11:44:07 	at java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2680)
11:44:07 	at java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:3155)
11:44:07 	at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:861)
11:44:07 	at java.io.ObjectInputStream.<init>(ObjectInputStream.java:357)
11:44:07 	at hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:48)
11:44:07 	at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:35)
11:44:07 	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:63)
11:44:07 Build step 'Build dependent downstream repositories (for PR builds)' marked build as failure
11:44:07 Terminating xvnc.

**Comment by wmedvede** [comment]
jenkins execute full downstream build

**Comment by hasys** [comment]
Hi @wmedvede, @romartin,

since Full Downstream Build takes all tree commits to make a build, I guess if it is green/fails only due to known issues on one PR the result can be used for all 3 commits.

**Pull request merged**
