### PR TITLE
AF-910

### PR DESCRIPTION
**Pull request by desmax74**
Fork of Takari 1.13.3 to provide failOnError configurable behaviour

### CODE REVIEW

**Comment by desmax74** [comment]
@porcelli

**Comment by porcelli** [comment]
jenkins please rebuild this

**Comment by domhanak** [comment]
@desmax74 Any updates here?

**Comment by porcelli** [comment]
not needed, new takari version has been released

**Comment by desmax74** [comment]
@domhanak just see this thread due to the mail received by the @porcelli close action, but never received a notification mail from you six days ago. @domhanak please in the future ping me on irc if you don't see my reply in one day, because I've the suspect that some mail are marked as spam by my mail provider.

**Pull request closed without merging**
