### PR TITLE
RH-237: [Guided Decision Table] Old tables don't recognize imports pr…

### PR DESCRIPTION
**Pull request by mbarkley**
…operly

### CODE REVIEW

**Comment by mbarkley** [comment]
@jomarko @manstis This fixes the reproducer in the relevant JIRA. When the `Import` class was first migrated, [this class](https://github.com/kiegroup/drools/blob/master/drools-workbench-models/drools-workbench-models-datamodel-api/src/main/java/org/drools/workbench/models/datamodel/imports/Import.java) was left behind to allow backwards compatibility.

Unfortunately, because it is a subtype, the (probably generated) equals method failed to recognize old imports on [this line](https://github.com/kiegroup/kie-wb-common/blob/master/kie-wb-common-widgets/kie-wb-common-ui/src/main/java/org/kie/workbench/common/widgets/client/datamodel/AsyncPackageDataModelOracleUtilities.java#L481).

**Comment by jomarko** [comment]
@mbarkley please could we add also some unit test for the class `AsyncPackageDataModelOracleUtilities` where we use both `org.kie.soup.project.datamodel.imports.Import` and `org.drools.workbench.models.datamodel.imports.Import`?

**Comment by manstis** [comment]
Thanks-you @mbarkley to be honest I was not expecting that to be the cause :-)

I didn't realise you'd left the old/original class around so thought we had a ton of duff XML in older repositories needing XStream aliasing to the new class. Glad it was a simple fix covering all use of Import.

**Comment by mbarkley** [comment]
> Thanks-you @mbarkley to be honest I was not expecting that to be the cause :-)

You and me both @manstis :)

**Pull request merged**
